spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gorod_drev
    username: root
    password: dasska123
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
#    hibernate:
#      ddl-auto: update

  flyway:
    baseline-on-migrate: true
